name: Everything
on:
  push:
    paths:
      - everything/**
      - .github/workflows/everything.yaml
    branches:
      - main

permissions:
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: acorn-io/actions-setup@v1
      - uses: acorn-io/actions-login@v1
        with:
          registry: ghcr.io
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}
      - name: Build & Push
        run: |
          DIR=everything
          cd ${DIR}
          acorn build -t ghcr.io/${{github.repository_owner}}/${DIR}:latest -p linux/amd64 -p linux/arm64 .
          acorn push ghcr.io/${{github.repository_owner}}/${DIR}:latest

