name: Redirect
on:
  push:
    paths:
      - redirect/**
      - .github/workflows/redirect.yaml
    branches:
      - main

permissions: write-all

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: acorn-io/actions-setup@v1
        with:
          token: ${{secrets.ACORN_TOKEN}}
      - uses: acorn-io/actions-login@v1
        with:
          registry: ghcr.io
          username: ${{secrets.REGISTRY_USERNAME}}
          password: ${{secrets.REGISTRY_PASSWORD}}
      - name: Build & Push
        run: |
          cd redirect
          acorn build -t ghcr.io/${{github.repository_owner}}/redirect:latest .
          acorn push ghcr.io/${{github.repository_owner}}/redirect:latest

